# Generated by Django 4.0.1 on 2022-01-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=16),
        ),
        migrations.CreateModel(
            name='GoodsInOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_operations.good')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_operations.organization')),
            ],
        ),
    ]
